export const countryList = [
    ["China", "86", "China", "CN", "中国"],
    ["China Macau", "853", "China Macau (中國澳門)", "CM", "中国澳门"],
    ["China HongKong", "852", "China HongKong (中国香港)", "CH", "中国香港"],
    ["China Taiwan", "886", "China Taiwan(中國台灣)", "CT", "中国台湾"],
    ["Afghanistan", "93", "Afghanistan (‫افغانستان‬‎)", "AF", "阿富汗"],
    ["Albania", "355", "Albania (Shqipëri)", "AL", "阿尔巴尼亚"],
    ["Algeria", "213", "Algeria (Algeria)", "DZ", "阿尔及利亚"],
    ["American Samoa", "1684", "American Samoa (American Samoa)", "AS", "美属萨摩亚"],
    ["Andorra", "376", "Andorra (Andorra)", "AD", "安道尔"],
    ["Angola", "244", "Angola (Angola)", "AO", "安哥拉"],
    ["Anguilla", "1264", "Anguilla (Anguilla)", "AI", "安圭拉"],
    ["Antigua and Barbuda", "1268", "Antigua and Barbuda (Antigua & Barbuda)", "AG", "安提瓜和巴布达"],
    ["Argentina", "54", "Argentina (Argentina)", "AR", "阿根廷"],
    ["Armenia", "374", "Armenia (Հայաստան)", "AM", "亚美尼亚"],
    ["Aruba", "297", "Aruba (Aruba)", "AW", "阿鲁巴"],
    ["Ascension Island", "247", "Ascension Island (Ascension Island)", "AC", "阿森松岛"],
    ["Australia", "61", "Australia (Australia)", "AU", "澳大利亚"],
    ["Austria", "43", "Austria (Österreich)", "AT", "奥地利"],
    ["Azerbaijan", "994", "Azerbaijan (Azərbaycan)", "AZ", "阿塞拜疆"],
    ["Bahamas", "1242", "Bahamas (Bahamas)", "BS", "巴哈马"],
    ["Bahrain", "973", "Bahrain (‫البحرين‬‎)", "BH", "巴林"],
    ["Bangladesh", "880", "Bangladesh (বাংলাদেশ)", "BD", "孟加拉国"],
    ["Barbados", "1246", "Barbados (Barbados)", "BB", "巴巴多斯"],
    ["Belarus", "375", "Belarus (Беларусь)", "BY", "白俄罗斯"],
    ["Belgium", "32", "Belgium (Belgium)", "BE", "比利时"],
    ["Belize", "501", "Belize (Belize)", "BZ", "伯利兹"],
    ["Benin", "229", "Benin (Bénin)", "BJ", "贝宁"],
    ["Bermuda", "1441", "Bermuda (Bermuda)", "BM", "百慕大"],
    ["Bhutan", "975", "Bhutan (འབྲུག)", "BT", "不丹"],
    ["Bolivia", "591", "Bolivia (Bolivia)", "BO", "玻利维亚"],
    ["Bonaire, Sint Eustatius, and Saba", "599", "Bonaire, Sint Eustatius, and Saba (Caribbean Netherlands)", "BQ", "荷属加勒比区"],
    ["Bosnia and Herzegovina", "387", "Bosnia and Herzegovina (Bosna i Hercegovina)", "BA", "波斯尼亚和黑塞哥维那"],
    ["Botswana", "267", "Botswana (Botswana)", "BW", "博茨瓦纳"],
    ["Brazil", "55", "Brazil (Brasil)", "BR", "巴西"],
    ["Brunei", "673", "Brunei (Brunei)", "BN", "文莱"],
    ["Bulgaria", "359", "Bulgaria (България)", "BG", "保加利亚"],
    ["Burkina Faso", "226", "Burkina Faso (Burkina Faso)", "BF", "布基纳法索"],
    ["Burundi", "257", "Burundi (Uburundi)", "BI", "布隆迪"],
    ["Cambodia", "855", "Cambodia (កម្ពុជា)", "KH", "柬埔寨"],
    ["Cameroon", "237", "Cameroon (Cameroun)", "CM", "喀麦隆"],
    ["Canada", "1", "Canada (Canada)", "CA", "加拿大"],
    ["Cape Verde", "238", "Cape Verde (Kabu Verdi)", "CV", "佛得角"],
    ["Cayman Islands", "1345", "Cayman Islands (Cayman Islands)", "KY", "开曼群岛"],
    ["Central African Republic", "236", "Central African Republic (République centrafricaine)", "CF", "中非共和国"],
    ["Chad", "235", "Chad (Tchad)", "TD", "乍得"],
    ["Chile", "56", "Chile (Chile)", "CL", "智利"],
    ["Colombia", "57", "Colombia (Colombia)", "CO", "哥伦比亚"],
    ["Comoros and Mayotte", "269", "Comoros and Mayotte (‫جزر القمر‬‎)", "KM", "科摩罗"],
    ["Congo Dem Rep", "243", "Congo Dem Rep (Jamhuri ya Kidemokrasia ya Kongo)", "CD", "刚果"],
    ["Congo", "242", "Congo (Congo-Brazzaville)", "CG", "刚果"],
    ["Cook Islands", "682", "Cook Islands (Cook Islands)", "CK", "库克群岛"],
    ["Costa Rica", "506", "Costa Rica (Costa Rica)", "CR", "哥斯达黎加"],
    ["Cote d'Ivoire", "225", "Cote d'Ivoire (Côte d’Ivoire)", "CI", "科特迪瓦"],
    ["Croatia", "385", "Croatia (Hrvatska)", "HR", "克罗地亚"],
    ["Curaçao", "599", "Curaçao (Curaçao)", "CW", "库拉索"],
    ["Cyprus", "357", "Cyprus (Κύπρος)", "CY", "塞浦路斯"],
    ["Czechia", "420", "Czechia (Česko)", "CZ", "捷克"],
    ["Denmark", "45", "Denmark (Danmark)", "DK", "丹麦"],
    ["Diego Garcia", "246", "Diego Garcia (British Indian Ocean Territory)", "IO", "英属印度洋领地"],
    ["Djibouti", "253", "Djibouti (Djibouti)", "DJ", "吉布提"],
    ["Dominica", "1767", "Dominica (Dominica)", "DM", "多米尼克"],
    ["Dominican Republic", "1809", "Dominican Republic (República Dominicana)", "DO", "多米尼加共和国"],
    ["Ecuador", "593", "Ecuador (Ecuador)", "EC", "厄瓜多尔"],
    ["Egypt", "20", "Egypt (‫مصر‬‎)", "EG", "埃及"],
    ["El Salvador", "503", "El Salvador (El Salvador)", "SV", "萨尔瓦多"],
    ["Equatorial Guinea", "240", "Equatorial Guinea (Guinea Ecuatorial)", "GQ", "赤道几内亚"],
    ["Eritrea", "291", "Eritrea (Eritrea)", "ER", "厄立特里亚"],
    ["Estonia", "372", "Estonia (Eesti)", "EE", "爱沙尼亚"],
    ["Ethiopia", "251", "Ethiopia (Ethiopia)", "ET", "埃塞俄比亚"],
    ["Falkland Islands", "500", "Falkland Islands (Falkland Islands (Islas Malvinas))", "FK", "福克兰群岛"],
    ["Faroe Islands", "298", "Faroe Islands (Føroyar)", "FO", "法罗群岛"],
    ["Fiji", "679", "Fiji (Fiji)", "FJ", "斐济"],
    ["Finland", "358", "Finland (Suomi)", "FI", "芬兰"],
    ["France", "33", "France (France)", "FR", "法国"],
    ["French Guiana", "594", "French Guiana (Guyane française)", "GF", "法属圭亚那"],
    ["French Polynesia", "689", "French Polynesia (Polynésie française)", "PF", "法属波利尼西亚"],
    ["Gabon", "241", "Gabon (Gabon)", "GA", "加蓬"],
    ["Gambia", "220", "Gambia (Gambia)", "GM", "冈比亚"],
    ["Georgia", "995", "Georgia (საქართველო)", "GE", "格鲁吉亚"],
    ["Germany", "49", "Germany (Deutschland)", "DE", "德国"],
    ["Ghana", "233", "Ghana (Gaana)", "GH", "加纳"],
    ["Gibraltar", "350", "Gibraltar (Gibraltar)", "GI", "直布罗陀"],
    ["Greece", "30", "Greece (Ελλάδα)", "GR", "希腊"],
    ["Greenland", "299", "Greenland (Kalaallit Nunaat)", "GL", "格陵兰"],
    ["Grenada", "1473", "Grenada (Grenada)", "GD", "格林纳达"],
    ["Guadeloupe", "590", "Guadeloupe (Guadeloupe)", "GP", "瓜德罗普"],
    ["Guatemala", "502", "Guatemala (Guatemala)", "GT", "危地马拉"],
    ["Guinea Bissau", "245", "Guinea Bissau (Guiné-Bissau)", "GW", "几内亚比绍"],
    ["Guinea", "224", "Guinea (Guinée)", "GN", "几内亚"],
    ["Guyana", "592", "Guyana (Guyana)", "GY", "圭亚那"],
    ["Haiti", "509", "Haiti (Haiti)", "HT", "海地"],
    ["Honduras", "504", "Honduras (Honduras)", "HN", "洪都拉斯"],
    ["Hungary", "36", "Hungary (Magyarország)", "HU", "匈牙利"],
    ["Iceland", "354", "Iceland (Ísland)", "IS", "冰岛"],
    ["India", "91", "India (भारत)", "IN", "印度"],
    ["Indonesia", "62", "Indonesia (Indonesia)", "ID", "印度尼西亚"],
    ["Iran", "98", "Iran (‫ایران‬‎)", "IR", "伊朗"],
    ["Iraq", "964", "Iraq (‫العراق‬‎)", "IQ", "伊拉克"],
    ["Ireland", "353", "Ireland (Ireland)", "IE", "爱尔兰"],
    ["Israel", "972", "Israel (‫ישראל‬‎)", "IL", "以色列"],
    ["Italy", "39", "Italy (Italia)", "IT", "意大利"],
    ["Jamaica", "1876", "Jamaica (Jamaica)", "JM", "牙买加"],
    ["Japan", "81", "Japan", "JP", "日本"],
    ["Jordan", "962", "Jordan (‫الأردن‬‎)", "JO", "约旦"],
    ["Kazakhstan", "7", "Kazakhstan (Казахстан)", "KZ", "哈萨克斯坦"],
    ["Kenya", "254", "Kenya (Kenya)", "KE", "肯尼亚"],
    ["Kiribati", "686", "Kiribati (Kiribati)", "KI", "基里巴斯"],
    ["Korea, North", "850", "Korea, North (북한)", "KP", "朝鲜"],
    ["Korea, South", "82", "Korea, South (대한민국)", "KR", "韩国"],
    ["Kuwait", "965", "Kuwait (‫الكويت‬‎)", "KW", "科威特"],
    ["Kyrgyzstan", "996", "Kyrgyzstan (Кыргызстан)", "KG", "吉尔吉斯斯坦"],
    ["Laos", "856", "Laos (ລາວ)", "LA", "老挝"],
    ["Latvia", "371", "Latvia (Latvija)", "LV", "拉脱维亚"],
    ["Lebanon", "961", "Lebanon (‫لبنان‬‎)", "LB", "黎巴嫩"],
    ["Lesotho", "266", "Lesotho (Lesotho)", "LS", "莱索托"],
    ["Liberia", "231", "Liberia (Liberia)", "LR", "利比里亚"],
    ["Libya", "218", "Libya (‫ليبيا‬‎)", "LY", "利比亚"],
    ["Liechtenstein", "423", "Liechtenstein (Liechtenstein)", "LI", "列支敦士登"],
    ["Lithuania", "370", "Lithuania (Lietuva)", "LT", "立陶宛"],
    ["Macedonia", "389", "Macedonia (Република Македонија)", "MK", "马其顿"],
    ["Madagascar", "261", "Madagascar (Madagasikara)", "MG", "马达加斯加"],
    ["Malawi", "265", "Malawi (Malawi)", "MW", "马拉维"],
    ["Malaysia", "60", "Malaysia (Malaysia)", "MY", "马来西亚"],
    ["Maldives", "960", "Maldives (Maldives)", "MV", "马尔代夫"],
    ["Mali", "223", "Mali (Mali)", "ML", "马里"],
    ["Malta", "356", "Malta (Malta)", "MT", "马耳他"],
    ["Marshall Islands", "692", "Marshall Islands (Marshall Islands)", "MH", "马绍尔群岛"],
    ["Martinique", "596", "Martinique (Martinique)", "MQ", "马提尼克"],
    ["Mauritania", "222", "Mauritania (‫موريتانيا‬‎)", "MR", "毛里塔尼亚"],
    ["Mexico", "52", "Mexico (México)", "MX", "墨西哥"],
    ["Micronesia", "691", "Micronesia (Micronesia)", "FM", "密克罗尼西亚"],
    ["Moldova", "373", "Moldova (Republica Moldova)", "MD", "摩尔多瓦"],
    ["Monaco", "377", "Monaco (Monaco)", "MC", "摩纳哥"],
    ["Mongolia", "976", "Mongolia (Монгол)", "MN", "蒙古"],
    ["Montenegro", "382", "Montenegro (Crna Gora)", "ME", "黑山"],
    ["Montserrat", "1664", "Montserrat (Montserrat)", "MS", "蒙特塞拉特"],
    ["Morocco", "212", "Morocco (Morocco)", "MA", "摩洛哥"],
    ["Mozambique", "258", "Mozambique (Moçambique)", "MZ", "莫桑比克"],
    ["Myanmar", "95", "Myanmar (မြန်မာ)", "MM", "缅甸"],
    ["Namibia", "264", "Namibia (Namibië)", "NA", "纳米比亚"],
    ["Nauru", "674", "Nauru (Nauru)", "NR", "瑙鲁"],
    ["Nepal", "977", "Nepal (नेपाल)", "NP", "尼泊尔"],
    ["Netherlands", "31", "Netherlands (Nederland)", "NL", "荷兰"],
    ["New Caledonia", "687", "New Caledonia (Nouvelle-Calédonie)", "NC", "新喀里多尼亚"],
    ["New Zealand", "64", "New Zealand (New Zealand)", "NZ", "新西兰"],
    ["Nicaragua", "505", "Nicaragua (Nicaragua)", "NI", "尼加拉瓜"],
    ["Niger", "227", "Niger (Nijar)", "NE", "尼日尔"],
    ["Nigeria", "234", "Nigeria (Nigeria)", "NG", "尼日利亚"],
    ["Norfolk Island", "672", "Norfolk Island (Norfolk Island)", "NF", "诺福克岛"],
    ["Northern Mariana Islands", "1", "Northern Mariana Islands (Northern Mariana Islands)", "MP", "北马里亚纳群岛"],
    ["Norway", "47", "Norway (Norge)", "NO", "挪威"],
    ["Oman", "968", "Oman (‫عُمان‬‎)", "OM", "阿曼"],
    ["Pakistan", "92", "Pakistan (‫پاکستان‬‎)", "PK", "巴基斯坦"],
    ["Palau", "680", "Palau (Palau)", "PW", "帕劳"],
    ["Palestine", "970", "Palestine (‫فلسطين‬‎)", "PS", "巴勒斯坦"],
    ["Panama", "507", "Panama (Panamá)", "PA", "巴拿马"],
    ["Papua New Guinea", "675", "Papua New Guinea (Papua New Guinea)", "PG", "巴布亚新几内亚"],
    ["Paraguay", "595", "Paraguay (Paraguay)", "PY", "巴拉圭"],
    ["Peru", "51", "Peru (Perú)", "PE", "秘鲁"],
    ["Philippines", "63", "Philippines (Philippines)", "PH", "菲律宾"],
    ["Poland", "48", "Poland (Polska)", "PL", "波兰"],
    ["Portugal", "351", "Portugal (Portugal)", "PT", "葡萄牙"],
    ["Puerto Rico", "1787", "Puerto Rico (Puerto Rico)", "PR", "波多黎各"],
    ["Qatar", "974", "Qatar (‫قطر‬‎)", "QA", "卡塔尔"],
    ["Reunion", "262", "Reunion (La Réunion)", "RE", "留尼汪"],
    ["Romania", "40", "Romania (România)", "RO", "罗马尼亚"],
    ["Russia", "7", "Russia (Россия)", "RU", "俄罗斯"],
    ["Rwanda", "250", "Rwanda (Rwanda)", "RW", "卢旺达"],
    ["Saint Barthélemy", "590", "Saint Barthélemy (Saint-Barthélemy)", "BL", "圣巴泰勒米"],
    ["Saint Helena", "290", "Saint Helena (St. Helena)", "SH", "圣赫勒拿"],
    ["Saint Kitts and Nevis", "1869", "Saint Kitts and Nevis (St. Kitts & Nevis)", "KN", "圣基茨和尼维斯"],
    ["Saint Lucia", "1758", "Saint Lucia (St. Lucia)", "LC", "圣卢西亚"],
    ["Saint Martin", "590", "Saint Martin (Saint-Martin)", "MF", "圣马丁岛"],
    ["Saint Pierre and Miquelon", "508", "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)", "PM", "圣皮埃尔和密克隆群岛"],
    ["Saint Vincent Grenadines", "1784", "Saint Vincent Grenadines (St. Vincent & Grenadines)", "VC", "圣文森特和格林纳丁斯"],
    ["Samoa", "685", "Samoa (Samoa)", "WS", "萨摩亚"],
    ["San Marino", "378", "San Marino (San Marino)", "SM", "圣马力诺"],
    ["Sao Tome and Principe", "239", "Sao Tome and Principe (São Tomé e Príncipe)", "ST", "圣多美和普林西比"],
    ["Saudi Arabia", "966", "Saudi Arabia (‫المملكة العربية السعودية‬‎)", "SA", "沙特阿拉伯"],
    ["Senegal", "221", "Senegal (Senegal)", "SN", "塞内加尔"],
    ["Serbia", "381", "Serbia (Србија)", "RS", "塞尔维亚"],
    ["Seychelles", "248", "Seychelles (Seychelles)", "SC", "塞舌尔"],
    ["Sierra Leone", "232", "Sierra Leone (Sierra Leone)", "SL", "塞拉利昂"],
    ["Singapore", "65", "Singapore (Singapore)", "SG", "新加坡"],
    ["Sint Maarten", "1721", "Sint Maarten (Sint Maarten)", "SX", "荷属圣马丁"],
    ["Slovakia", "421", "Slovakia (Slovensko)", "SK", "斯洛伐克"],
    ["Slovenia", "386", "Slovenia (Slovenija)", "SI", "斯洛文尼亚"],
    ["Solomon Islands", "677", "Solomon Islands (Solomon Islands)", "SB", "所罗门群岛"],
    ["Somalia", "252", "Somalia (Soomaaliya)", "SO", "索马里"],
    ["South Africa", "27", "South Africa (South Africa)", "ZA", "南非"],
    ["South Sudan", "211", "South Sudan (‫جنوب السودان‬‎)", "SS", "南苏丹"],
    ["Spain", "34", "Spain (España)", "ES", "西班牙"],
    ["Sri Lanka", "94", "Sri Lanka (ශ්‍රී ලංකාව)", "LK", "斯里兰卡"],
    ["Sudan", "249", "Sudan (‫السودان‬‎)", "SD", "苏丹"],
    ["Suriname", "597", "Suriname (Suriname)", "SR", "苏里南"],
    ["Swaziland", "268", "Swaziland (Swaziland)", "SZ", "斯威士兰"],
    ["Sweden", "46", "Sweden (Sverige)", "SE", "瑞典"],
    ["Switzerland", "41", "Switzerland (Schweiz)", "CH", "瑞士"],
    ["Syria", "963", "Syria (‫سوريا‬‎)", "SY", "叙利亚"],
    ["Tajikistan", "992", "Tajikistan (Tajikistan)", "TJ", "塔吉克斯坦"],
    ["Tanzania", "255", "Tanzania (Tanzania)", "TZ", "坦桑尼亚"],
    ["Thailand", "66", "Thailand (ไทย)", "TH", "泰国"],
    ["Timor-Leste", "670", "Timor-Leste (Timor-Leste)", "TL", "东帝汶"],
    ["Togo", "228", "Togo (Togo)", "TG", "多哥"],
    ["Tokelau", "690", "Tokelau (Tokelau)", "TK", "托克劳"],
    ["Tonga", "676", "Tonga (Tonga)", "TO", "汤加"],
    ["Trinidad and Tobago", "1868", "Trinidad and Tobago (Trinidad & Tobago)", "TT", "特立尼达和多巴哥"],
    ["Tunisia", "216", "Tunisia (Tunisia)", "TN", "突尼斯"],
    ["Turkey", "90", "Turkey (Türkiye)", "TR", "土耳其"],
    ["Turkmenistan", "993", "Turkmenistan (Turkmenistan)", "TM", "土库曼斯坦"],
    ["Turks and Caicos", "1649", "Turks and Caicos (Turks & Caicos Islands)", "TC", "特克斯和凯科斯群岛"],
    ["Tuvalu", "688", "Tuvalu (Tuvalu)", "TV", "图瓦卢"],
    ["Uganda", "256", "Uganda (Uganda)", "UG", "乌干达"],
    ["Ukraine", "380", "Ukraine (Україна)", "UA", "乌克兰"],
    ["United Arab Emirates", "971", "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)", "AE", "阿拉伯联合酋长国"],
    ["United Kingdom", "44", "United Kingdom (United Kingdom)", "GB", "英国"],
    ["United States", "1", "United States", "US", "美国"],
    ["Uruguay", "598", "Uruguay (Uruguay)", "UY", "乌拉圭"],
    ["Uzbekistan", "998", "Uzbekistan (Oʻzbekiston)", "UZ", "乌兹别克斯坦"],
    ["Vatican City", "379", "Vatican City (Città del Vaticano)", "VA", "梵蒂冈"],
    ["Venezuela", "58", "Venezuela (Venezuela)", "VE", "委内瑞拉"],
    ["Vietnam", "84", "Vietnam (Việt Nam)", "VN", "越南"],
    ["Virgin Islands, British", "1284", "Virgin Islands, British (British Virgin Islands)", "VG", "英属维尔京群岛"],
    ["Virgin Islands, US", "1340", "Virgin Islands, US (U.S. Virgin Islands)", "VI", "美属维尔京群岛"],
    ["Wallis and Futuna", "681", "Wallis and Futuna (Wallis & Futuna)", "WF", "瓦利斯和富图纳"],
    ["Yemen", "967", "Yemen (‫اليمن‬‎)", "YE", "也门"],
    ["Zambia", "260", "Zambia (Zambia)", "ZM", "赞比亚"],
    ["Zimbabwe", "263", "Zimbabwe (Zimbabwe)", "ZW", "津巴布韦"],
  ]

